menu_items = [
    {
        "id": 1,
        "name": "Cappuccino",
        "category": "coffee",
        "price": 140.0,
        "description": "Rich espresso topped with velvety milk foam.",
        "available": True,
    },
    {
        "id": 2,
        "name": "Latte",
        "category": "coffee",
        "price": 150.0,
        "description": "Smooth espresso with steamed milk and a light layer of foam.",
        "available": True,
    },
    {
        "id": 3,
        "name": "Espresso",
        "category": "coffee",
        "price": 120.0,
        "description": "Bold and intense single-shot espresso.",
        "available": True,
    },
    {
        "id": 4,
        "name": "Masala Chai",
        "category": "tea",
        "price": 80.0,
        "description": "Traditional spiced tea brewed with milk and aromatic herbs.",
        "available": True,
    },
    {
        "id": 5,
        "name": "Cold Coffee",
        "category": "coffee",
        "price": 170.0,
        "description": "Iced coffee blended with milk and a hint of chocolate.",
        "available": True,
    },
    {
        "id": 6,
        "name": "Veg Sandwich",
        "category": "sandwich",
        "price": 180.0,
        "description": "Fresh vegetables and sauces layered in toasted bread.",
        "available": True,
    },
    {
        "id": 7,
        "name": "Chicken Club Sandwich",
        "category": "sandwich",
        "price": 220.0,
        "description": "Grilled chicken, lettuce, and creamy sauce in a classic club.",
        "available": True,
    },
    {
        "id": 8,
        "name": "Croissant",
        "category": "bakery",
        "price": 110.0,
        "description": "Buttery, flaky pastry perfect with coffee.",
        "available": True,
    },
    {
        "id": 9,
        "name": "Chocolate Brownie",
        "category": "dessert",
        "price": 130.0,
        "description": "Warm chocolate brownie with a fudgy center.",
        "available": True,
    },
    {
        "id": 10,
        "name": "Cafe Combo",
        "category": "combo",
        "price": 260.0,
        "description": "A signature coffee and sandwich combo for a quick cafe break.",
        "available": True,
    },
]
